POST http://localhost:4567/createuser HTTP/1.1

{
    "username": "asd",
    "password": "asda"
}

###

POST http://10.114.32.45:8080/createuser HTTP/1.1

{
    "username": "sad",
    "password": "asda"
}

###

DELETE http://localhost:4567/api/user/delete/asdaa HTTP/1.1
Authorization: Basic YXNkOllYTmtZWE5rWVE9PQ==

###

OPTIONS http://localhost:4567/exists/asd HTTP/1.1

###

post http://localhost:4567/login HTTP/1.1

{
    "username": "asd",
    "password": "asda"
}

###

PUT http://localhost:4567/api/user/update
Authorization: Basic YXNkOllYTmtZWE5rWVE9PQ==

{   
    "username": "asd",
    "sahkoposti": "www.sss.ddd"
}

