import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
  en: {
    address: "Address",
    about: "About us",
    accnumber: "Account number",
    archive: "Archive",
    bank: "Bank",
    businessid: "Business ID",
    clear: "Clear",
    create: "Create",
    cancel: "Cancel",
    company: "Company",
    companyName: "Company name",
    contactP: "Contact person",
    customer: "Customer",
    customers: "Customers",
    dateOfInvoice: "Date of the invoice",
    delayRate: "Delay rate",
    delete: "Delete",
    email: "Email",
    emptyproductlist: "No products added",
    enterInfo: "Enter your info",
    front: "Frontpage",
    info: "Your info",
    invoiceDue: "Invoice due date",
    invoiceRec: "Invoice receiver",
    invoiceInfo: "Invoice information",
    invoiceMsg: "Invoice message",
    invoiceNmb: "Invoice number",
    invoiceRecipient: "Invoice recipient info",
    invoiceProducts: "Invoice products",
    latestInvoices: "Latest invoices",
    logout: "Log out",
    name: "Name",
    newInvoice: "New invoice",
    newCustomer: "Add a new customer",
    preview: "Preview",
    priceGross: "Gross price",
    priceNet: "Net price",
    price: "Price",
    postal: "Postal address",
    postaldist: "Postal district",
    postalnmb: "Postal number",
    productAmount: "Number of pieces",
    productinfo: "Product info",
    productName: "Product name",
    productadd: "Add product",
    remarkTime: "Remark time",
    required: "Required field",
    refnmb: "Reference number",
    signin: "Sign in",
    signinInfo: "Sign-in info",
    signup: "Sign up",
    settings: "Settings",
    tax: "Tax",
    toFrontpage: "To the frontpage",
    total: "Total",
    update: "Update",
    updateProduct: "Update product",
    updateProductExp: "To update a product, re-enter all the information for the products and press update. Press cancel to cancel.",
    vat: "VAT"
  },
  fi: {
    accnumber: "Tilinumero",
    address: "Osoite",
    about: "Tietoa meistä",
    archive: "Arkisto",
    bank: "Pankki",
    businessid: "Y-tunnus",
    cancel: "Peruuta",
    clear: "Tyhjennä",
    company: "Yritys",
    companyName: "Yrityksen nimi",
    contactP: "Yhteyshenkilö",
    create: "Luo",
    customer: "Asiakas",
    customers: "Asiakkaat",
    dateOfInvoice: "Laskun päiväys",
    delayRate: "Myöhästymis korko",
    delete: "Poista",
    enterInfo: "Syötä tietosi",
    email: "Sähköposti",
    emptyproductlist: "Ei vielä lisättyjä tuotteita",
    front: "Etusivu",
    info: "Omat tiedot",
    invoiceDue: "Laskun eräpäivä",
    invoiceRec: "Laskun vastaanottaja",
    invoiceInfo: "Laskun tiedot",
    invoiceMsg: "Laskuviesti",
    invoiceNmb: "Laskun numero",
    invoiceRecipient: "Laskunsaajan tiedot",
    invoiceProducts: "Tuotteet laskulla",
    logout: "Kirjaudu ulos",
    latestInvoices: "Viimeisimmät laskut",
    name: "Nimi",
    newInvoice: "Uusi lasku",
    newCustomer: "Lisää uusi asiakas",
    preview: "Esikatsele",
    priceGross: "Bruttohinta",
    priceNet: "Nettohinta",
    price: "Hinta",
    postal: "Postinumero ja -toimipaikka",
    postalnmb: "Postinumero",
    postaldist: "Postitoimipaikka",
    productAmount: "Kappalemäärä",
    productinfo: "Tuotteiden tiedot",
    productName: "Tuotteen nimi",
    productadd: "Lisää tuote",
    remarkTime: "Huomautusaika",
    required: "Pakollinen kenttä",
    refnmb: "Viite numero",
    signin: "Kirjaudu sisään",
    signinInfo: "Kirjautumistiedot",
    signup: "Rekisteröityminen",
    settings: "Asetukset",
    tax: "Vero",
    total: "Yhteensä",
    toFrontpage: "Etusivulle",
    update: "Päivitä",
    updateProduct: "Tuotteen päivitys",
    updateProductExp: "Päivittääksesi tuotteen, syötä tuotteet kaikki tiedot uudelleen ja paina päivitä. Paina peruuta peruuttaaksesi.",
    clear: "Tyhjennä",
    vat: "ALV"
  },
  alb: {
    archive: "Arkivi",
    address: "Adresë",
    accnumber: "Numri i llogarisë",
    about: "Rreth nesh",
    bank: "Bankë",
    businessid: "Id e biznesit",
    cancel: "Anuloj",
    company: "Kompani",
    companyName: "Emri i Kompanise",
    contactP: "Personi i kontaktit",
    create: "Krijoj",
    customer: "Klient",
    customers: "Klientët",
    clear: "Qartë",
    dateOfInvoice: "Data e një fature",
    delayRate: "Shkalla e vonesës",
    delete: "Fshij",
    email: "Email",
    enterInfo: "Shkruani informacionin tuaj",
    emptyproductlist: "Asnjë produkt i shtuar",
    front: "Faqja Kryesore",
    info: "Informacione vetanake",
    invoiceDue: "Data e faturës",
    invoiceRec: "Marrësi i faturës",
    invoiceInfo: "Informacione për faturën",
    invoiceMsg: "Porosia e faturës",
    invoiceNmb: "Numri i faturës",
    invoiceRecipient: "Informacioni i marrësit të faturës",
    invoiceProducts: "Produktet e faturës",
    latestInvoices: "Faturat e fundit",
    logout: "Shkyç",
    name: "Emër",
    newInvoice: "Faturë e re",
    newCustomer: "Shtoni një klient të ri",
    preview: "Dischurtja",
    priceGross: "çmimi bruto",
    priceNet: "çmimi neto",
    price: "çmimi",
    postal: "Adresa postale",
    postalnmb: "Numrin postar",
    postaldist: "Rrethi postar",
    productAmount: "Numri i pjesëve",
    productinfo: "Informacion për produktin",
    productName: "Emri i produktit",
    productadd: "Shtoni produkt",
    remarkTime: "Të gjitha vërejtjet",
    required: "Fusha e kërkuar",
    refnmb: "Numri i referencës",
    settings: "Faqosje",
    signin: "Hyni",
    signinInfo: "Informacioni i hyrjes",
    signup: "Regjistrohu",
    tax: "Taksë",
    total: "Total",
    toFrontpage: "Te faqja kryesore",
    update: "Përditësimi",
    updateProduct: "Produkt i azhurnuar",
    updateProductExp: "Për të azhurnuar një produkt, rivendosni të gjitha informacionet për produktet dhe shtypni azhurnimin. Shtypni anulimin për të anuluar.",
    vat: "TVSH"
  }
});

export default strings